### ISSUE TITLE
可以把DeepSeek也加上吗？

### ISSUE THREAD

**Issue by blmdxiao** [EvalsOne/UnionLLM#1]

**Comment by blmdxiao** [comment]
[LiteLLM](https://github.com/BerriAI/litellm)已经支持了

**Comment by quentinzhang** [comment]
UnionLLM新版本已经增加了对于DeepSeek和零一万物模型的原生支持。

此外，因为它们的接口与OpenAI格式兼容，也可以通过UnionLLM调用LiteLLM的custom proxy来实现。像这样：
completion = unionchat(custom_llm_provider="openai", model=model, api_key="your-api-key", api_base="https://api.stepfun.com/v1", messages=messages, **params)

**Comment by luckycat0426** [comment]
请问能否支持字节豆包

**Comment by quentinzhang** [comment]
> 请问能否支持字节豆包

好的，我去研究一下。

**Comment by luckycat0426** [comment]
> > 请问能否支持字节豆包
> 
> 好的，我去研究一下。

 已添加字节豆包支持 #2   请审阅代码

**Comment by quentinzhang** [comment]
> > > 请问能否支持字节豆包
> > 
> > 
> > 好的，我去研究一下。
> 
> 已添加字节豆包支持 #2 请审阅代码

谢谢你的贡献！做了一些代码的修改，请确认
