### ISSUE TITLE
【bug】豆包的 "role": "system" 没有生效

### ISSUE THREAD

**Issue by shenxgan** [EvalsOne/UnionLLM#3]
```python
    messages=[
        {"role": "system", "content": "你的每次回复都在50字以内"},
        {"content": msg, "role": "user"}
    ],
```
上述同样的参数，用官方的示例代码调用，可正常回复在50字以内。但是使用本项目调用没有效果

**Comment by quentinzhang** [comment]
是因为当时增加对豆包支持的时候，消息列表中不支持system角色，所以做了特殊处理。具体在doubao.py的to_formatted_prompt方法中。

现在豆包已经支持系统消息了，稍后我会发布一个新版修复这个问题。
